name: build and test c
on: push
permissions:
  contents: write  # needed to deploy coverage
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }} # we might make multiple deployments in quick succession
    steps:
    - uses: actions/checkout@v3
    - uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: '1.3.1-0'
        environment-file: dev-conda-env.yml
        environment-name: test
        init-shell: >-
          bash
        cache-environment: true
    - name: install repo code
      shell: bash -el {0}
      run: |
        python -m pip install .
    - name: generate test data
      shell: bash -el {0}
      run: |
        python -m ipykernel install --user --name gha-kernel
        papermill -p SAVE_PATH trees notebooks/TestCases.ipynb TestCases.ipynb -k gha-kernel
        ls -la trees
    - name: build and test
      working-directory: c
      shell: bash -el {0}
      run: |
        meson setup -Db_coverage=true build
        ninja -C build test coverage
    - name: deploy code coverage
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: /home/runner/work/ts-two-locus-proto/ts-two-locus-proto/c/build/meson-logs/coveragereport
    # - name: save coverage report
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: coveragereport
    #     path: /home/runner/work/ts-two-locus-proto/ts-two-locus-proto/c/build/meson-logs/coveragereport
