name: build and test c
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: setup meson and ninja
      run:
        python -m pip install 'meson==1.1.1' 'ninja==1.11.1'
    - name: build and test
      working-directory: c
      run:
        meson setup build
        ninja -C build test
