name: build and test c
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: '1.3.1-0'
        environment-file: dev-conda-env.yml
        environment-name: test
        init-shell: >-
          bash
        cache-environment: true
    - name: build and test
      working-directory: c
      run: |
        echo $0
        export
        meson setup build
        ninja -C build test
