name: build and test c
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: Cache conda
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if env yaml hasn't changed
        CACHE_NUMBER: 0
      with:
        path: ${{ env.CONDA }}/envs
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('dev-conda-env.yml') }}
    - name: setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge,bioconda
        environment-file: dev-conda-env.yml
    - name: build and test
      working-directory: c
      shell: bash -eo pipefail {0}
      run: |
        conda init bash
        source /home/runner/.bashrc
        conda activate test
        meson setup build
        ninja -C build test
